name: Build Image

on: [push, pull_request, workflow_dispatch]

env:
  ENDPOINT: "eshork/universal-openvpn"
  BRANCH: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --no-cache \
           --label "org.opencontainers.image.source=https://github.com/eshork/universal-openvpn" \
           --label "org.opencontainers.image.description=openvpn docker-mod" \
           --label "org.opencontainers.image.licenses=MIT" \
           --tag ghcr.io/${ENDPOINT}:$(echo $GITHUB_SHA | head -c7) \
           --tag ghcr.io/${ENDPOINT}:${{ github.sha }} \
           --tag ghcr.io/${ENDPOINT}:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub
        run: |
          docker push ghcr.io/${ENDPOINT}:${{ github.sha }}
          docker push ghcr.io/${ENDPOINT}:$(echo $GITHUB_SHA | head -c7)

      - name: Push :latest image to GitHub
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ghcr.io/${ENDPOINT}:latest
