name: Build Image

on: [push, pull_request, workflow_dispatch]

env:
  ENDPOINT: "eshork/universal-openvpn"
  BRANCH: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Build image
        run: |
          docker build --no-cache -t ${{ github.sha }} \
           --label "org.opencontainers.image.source=https://github.com/eshork/universal-openvpn" \
           --label "org.opencontainers.image.description=openvpn docker-mod" \
           --label "org.opencontainers.image.licenses=MIT" .

      - name: Tag image
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
        run: |
          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}
          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}:${{ github.sha }}

      - name: Login to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u $CR_USER --password-stdin

      - name: Push tags to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
        run: |
          docker push ghcr.io/${ENDPOINT}:${{ github.sha }}
          docker push ghcr.io/${ENDPOINT}

